// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUT8W-4sFcSrO3pIW9IQPtEP3QA_CtOPI',
    appId: '1:598730973278:web:57f9b1b004b475e90094cf',
    messagingSenderId: '598730973278',
    projectId: 'orientation-linguistique-2025',
    authDomain: 'orientation-linguistique-2025.firebaseapp.com',
    storageBucket: 'orientation-linguistique-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxNoUDVqjpW0tculy1oAKd2IVbhPj9WM',
    appId: '1:598730973278:android:66607f1eea09986b0094cf',
    messagingSenderId: '598730973278',
    projectId: 'orientation-linguistique-2025',
    storageBucket: 'orientation-linguistique-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-pS1yF3bSi5Kgc2eyeQaKwaZh47-BUjg',
    appId: '1:598730973278:ios:6ba22bf4f6f9e8900094cf',
    messagingSenderId: '598730973278',
    projectId: 'orientation-linguistique-2025',
    storageBucket: 'orientation-linguistique-2025.firebasestorage.app',
    iosBundleId: 'com.example.orientationLinguistiqueAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-pS1yF3bSi5Kgc2eyeQaKwaZh47-BUjg',
    appId: '1:598730973278:ios:6ba22bf4f6f9e8900094cf',
    messagingSenderId: '598730973278',
    projectId: 'orientation-linguistique-2025',
    storageBucket: 'orientation-linguistique-2025.firebasestorage.app',
    iosBundleId: 'com.example.orientationLinguistiqueAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUT8W-4sFcSrO3pIW9IQPtEP3QA_CtOPI',
    appId: '1:598730973278:web:59c0c0da056ef30e0094cf',
    messagingSenderId: '598730973278',
    projectId: 'orientation-linguistique-2025',
    authDomain: 'orientation-linguistique-2025.firebaseapp.com',
    storageBucket: 'orientation-linguistique-2025.firebasestorage.app',
  );
}
